print(" _      ____  ____  ____  _      ____    ____  ____  ____     _  _____ ____ _____ ")
print("/ \__/|/  _ \/ ___\/  _ \/ \  /|/ ___\  /  __\/  __\/  _ \   / |/  __//    |___ __\ ")
print("| |\/||| / \||    \| / \|| |\ |||    \  |  \/||  \/|| / \|   | ||  \  |  /   / \  ") 
print("| |  ||| |-||\___ || \_/|| | \||\___ |  |  __/|    /| \_/|/\_| ||  /_ |  \_  | |  ") 
print("\_/  \|\_/ \|\____/\____/\_/  \|\____/  \_/   \_/\_\\____/\____/\____\\____/ \_/  ")
print("hi what is your name?")
name =input("")
print(f"Hello {name} and welcome to Masons project today i will be making sure your feeling great")
print("How are you doing today")
input("")
print(f"{name} today we are going to make you feel even better")
input("")
print("is there anything you would want to talk about if so i can listen")
input("")
print(f"{name} ok would you want me to tell you a joke")
input("")
print("what do you call a fake noodle")
input("")
print("An im,pasta")
print("ha ha did you like it")
input("")
print("thats great")
print("it is time for me to go bye")